version: 2
updates:
  - package-ecosystem: pip
    directory: "/tests/rf_versions_matrix/rf7/"
    schedule:
      interval: "daily"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
