ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
DISABLE_ERRORS_LINTERS:
  - RST_RSTCHECK
EXCLUDED_DIRECTORIES:
  - build
PRE_COMMANDS:
  - command: pip install robotframework-robocop[doc]
    venv: rstcheck
