ENABLE_LINTERS:
  - PYTHON_RUFF
  - PYTHON_MYPY
  - MARKDOWN_MARKDOWNLINT

VALIDATE_ALL_CODEBASE: true
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_ARGUMENTS: --force-exclude
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_MYPY_CLI_LINT_MODE: project
PYTHON_MYPY_ARGUMENTS: --install-types --non-interactive
MARKDOWN_MARKDOWNLINT_ARGUMENTS: --disable MD046
