ENABLE_LINTERS:
  - PYTHON_RUFF
  - MARKDOWN_MARKDOWNLINT

VALIDATE_ALL_CODEBASE: true
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_ARGUMENTS: --force-exclude
MARKDOWN_MARKDOWNLINT_ARGUMENTS: --disable MD046
