ENABLE_LINTERS:
  - PYTHON_RUFF
  - MARKDOWN_MARKDOWNLINT

VALIDATE_ALL_CODEBASE: true
PYTHON_RUFF_RULES_PATH: .
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
MARKDOWN_MARKDOWNLINT_ARGUMENTS: --disable MD046