ENABLE_LINTERS:
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_ISORT
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
DISABLE_ERRORS_LINTERS:
  - RST_RSTCHECK
EXCLUDED_DIRECTORIES:
  - build
PRE_COMMANDS:
  - command: pip install robotframework-robocop[dev]
    venv: pylint
  - command: pip install robotframework-robocop[doc]
    venv: rstcheck
