- id: robocop
  name: robocop
  description: "Robot Framework linter"
  entry: robocop check --force-exclude
  language: python
  files: '.*\.(robot|resource)$'
  minimum_pre_commit_version: "2.9.2"

- id: robocop-format
  name: robocop-format
  description: "Robot Framework formatter"
  entry: robocop format --force-exclude
  language: python
  files: '.*\.(robot|resource)$'
  minimum_pre_commit_version: "2.9.2"