---
version: 2

mkdocs:
  configuration: mkdocs.yml

build:
   os: ubuntu-24.04
   tools:
      python: "3.13"
   jobs:
      create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
         - uv venv
      install:
         - uv sync --group doc
      build:
         html:
           - uv run mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml
