name: Bug report
description: File a bug report
title: '[Bug] '
labels: 'bug'
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: "Bug details"
    validations:
      required: true
 - type: input
    id: platform
    attributes:
      label: Operating System
      description: On what OS it does happen?
      placeholder: Windows
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Latest Robocop version
      description: Do you use latest version of Robocop?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for your report!
