name: Bug report
description: File a bug report
title: '[Bug] '
labels: 'bug'
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: "Bug details"
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Operating System
      description: On what OS does it happen?
      placeholder: Windows
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Robocop version
      description: What version of Robocop are you using? You can check it by running `robocop -v`
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for your report!
