"""
Generate a documented Robocop configuration file with all available options.

The generated file lists every global option, linter rule and formatter together with their default
values and short descriptions. All options are written as comments, so the generated file reproduces
Robocop's default behaviour until the user uncomments and edits the options they want to change.
"""

from __future__ import annotations

import textwrap
from typing import TYPE_CHECKING, Any

from robocop import __version__
from robocop.config import defaults
from robocop.linter.rules import RuleParam, RuleSeverity

if TYPE_CHECKING:
    from collections.abc import Iterable

    from robocop.formatter.formatters import Formatter
    from robocop.linter.rules import Rule
    from robocop.version_handling import Version

INDENT = "    "


def format_value(value: Any) -> str:
    """Render a default value as it would be written in a ``name.param=value`` configure entry."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, RuleSeverity):
        return value.value
    if isinstance(value, (list, tuple, set)):
        return ",".join(format_value(item) for item in value)
    return str(value)


def _rule_category(rule: Rule) -> str:
    """Return the alphabetic prefix of the rule id (e.g. ``COM`` from ``COM01``)."""
    return "".join(char for char in rule.rule_id if char.isalpha())


def _wrap_comment(text: str, indent: str) -> list[str]:
    """Wrap description text into commented lines that do not exceed the line length limit."""
    wrapped = textwrap.wrap(text, width=115 - len(indent))
    return [f"{indent}# {line}" for line in wrapped] if wrapped else []


def _iter_rule_params(rule: Rule) -> Iterable[tuple[str, str, str, Any]]:
    """Yield ``(name, type, description, default)`` for every configurable rule parameter."""
    for param in rule.config.values():
        if param.name in ("enabled", "severity"):
            continue
        if isinstance(param, RuleParam):
            yield param.name, param.param_type, param.desc, param.default
        else:  # SeverityThreshold and similar parameters without a plain default
            yield (
                param.name,
                "severity_threshold",
                "Set the rule severity based on the configured parameter value thresholds.",
                "warning=<value>:error=<value>",
            )


def _generate_header() -> list[str]:
    return [
        "# " + "=" * 100,
        "# Robocop configuration file",
        f"# Generated by `robocop config init` (Robocop {__version__}).",
        "#",
        "# This file documents every available Robocop option with its default value.",
        "# All options are commented out, so as-is this file reproduces Robocop's default behaviour.",
        "# Uncomment and edit the options you want to change.",
        "#",
        "# Full documentation is available at https://robocop.dev .",
        "# " + "=" * 100,
        "",
    ]


def _toml_render(value: Any) -> str:
    """Render a Python value as a TOML scalar/array for a commented ``key = value`` line."""
    if value is None:
        return '""'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, dict):
        return "{}"
    if isinstance(value, (list, tuple, set)):
        return "[" + ", ".join(_toml_render(item) for item in value) + "]"
    return f'"{value}"'


def _render_options(header: str, options: list[tuple[str, Any, str]]) -> list[str]:
    lines = [header, ""]
    for name, default, desc in options:
        lines.extend(_wrap_comment(desc, ""))
        lines.append(f"# {name} = {_toml_render(default)}")
        lines.append("")
    return lines


def _global_options(target_version: Version) -> list[str]:
    """Commented global (``[tool.robocop]``) options with their defaults."""
    options: list[tuple[str, Any, str]] = [
        ("include", [], "Additional paths (glob patterns) to include on top of the default ones."),
        ("default_include", list(defaults.DEFAULT_INCLUDE), "Override the default included paths."),
        ("exclude", [], "Additional paths (glob patterns) to exclude on top of the default ones."),
        ("default_exclude", list(defaults.DEFAULT_EXCLUDE), "Override the default excluded paths."),
        ("force_exclude", defaults.FORCE_EXCLUDE, "Enforce exclusions even for paths passed directly."),
        ("language", [], "Additional languages used to parse Robot Framework files."),
        (
            "target_version",
            str(target_version.release[0]),
            "Robot Framework major version rules are evaluated against.",
        ),
        (
            "project",
            True,
            "Run project level rules. By default they run when a project rule is selected; "
            "set to false (or use --no-project) to always skip them.",
        ),
        ("analyze_libraries", defaults.ANALYZE_LIBRARIES, "Import libraries to analyze their keywords."),
        ("load_library_timeout", defaults.LOAD_LIBRARY_TIMEOUT, "Timeout (seconds) for importing a library."),
        ("library_workers", defaults.LIBRARY_WORKERS, "Use worker processes to import libraries."),
        ("ignored_libraries", [], "Libraries that should not be imported and analyzed."),
        ("cache", True, "Enable caching of the analysis results."),
        ("cache_dir", defaults.CACHE_DIR_NAME, "Directory used to store the cache."),
        ("verbose", defaults.VERBOSE, "Print more information during the run."),
        ("silent", defaults.SILENT, "Do not print any output."),
    ]
    return _render_options("[tool.robocop]", options)


def _lint_options() -> list[str]:
    """Commented linter (``[tool.robocop.lint]``) options with their defaults."""
    options: list[tuple[str, Any, str]] = [
        ("ignore", [], "Disable selected rules."),
        ("fixable", [], "Only apply automatic fixes for the selected rules."),
        ("unfixable", [], "Never apply automatic fixes for the selected rules."),
        ("per_file_ignores", {}, "Disable rules only for the paths matching the given patterns."),
        ("issue_format", defaults.DEFAULT_ISSUE_FORMAT, "Format of the printed issues."),
        ("threshold", RuleSeverity.INFO.value, "Only report issues with severity equal or above the threshold."),
        ("custom_rules", [], "Paths to custom rules to load."),
        ("reports", [], "Enable selected reports."),
        ("persistent", defaults.PERSISTENT, "Store the run results and compare them on the next run."),
        ("compare", defaults.COMPARE, "Compare the results with the previously stored run."),
        ("exit_zero", defaults.EXIT_ZERO, "Always return a 0 (non-error) exit code, even on issues."),
        ("fix", defaults.FIX, "Automatically fix the issues that support it."),
        ("unsafe_fixes", defaults.UNSAFE_FIXES, "Apply also fixes marked as unsafe."),
        ("diff", defaults.FIX_DIFF, "Print the diff of the changes made by the fixes."),
    ]
    return _render_options("[tool.robocop.lint]", options)


def _format_options() -> list[str]:
    """Commented formatter (``[tool.robocop.format]``) options with their defaults."""
    options: list[tuple[str, Any, str]] = [
        ("select", [], "Select which formatters to run. Empty value runs all formatters enabled by default."),
        ("extend_select", [], "Enable extra formatters on top of the default ones."),
        ("force_order", defaults.FORCE_ORDER, "Run the formatters in the order they were selected."),
        ("overwrite", True, "Write the changes back to the source files."),
        ("diff", defaults.DIFF, "Print the diff of the changes made by the formatters."),
        ("check", defaults.CHECK, "Do not overwrite files, only return the status of the changes."),
        ("color", defaults.COLOR, "Enable colored output."),
        ("reruns", defaults.RERUNS, "Number of formatting reruns to enforce a stable result."),
        ("start_line", None, "Format only the code starting from this line."),
        ("end_line", None, "Format only the code up to this line."),
        ("space_count", 4, "Number of spaces used as a separator."),
        ("indent", None, "Number of spaces used for indentation (defaults to space_count)."),
        ("continuation_indent", None, "Number of spaces used for the continuation indent (defaults to space_count)."),
        ("separator", "space", "Type of separator used between the tokens: `space` or `tab`."),
        ("line_length", 120, "Maximum line length used by the formatters."),
        ("line_ending", "native", "Line ending used in the formatted files: `native`, `windows`, `unix` or `auto`."),
    ]
    return _render_options("[tool.robocop.format]", options)


def _grouped_by_category(rules: list[Rule]) -> dict[str, list[Rule]]:
    grouped: dict[str, list[Rule]] = {}
    for rule in rules:
        grouped.setdefault(_rule_category(rule), []).append(rule)
    return grouped


def _rule_select_lines(rules: list[Rule], target_version: Version) -> list[str]:
    """
    Build the ``select`` array listing every rule with a short inline comment.

    Rules enabled by default are listed as active entries; rules disabled by default (non-default and
    project rules) are listed commented out so they can be enabled by uncommenting them.
    """
    lines = [
        "# Rules to run. Each active entry enables a rule; remove or comment out an entry to disable it.",
        "# Rules disabled by default (non-default and project rules) are listed commented out - uncomment",
        "# an entry to enable the rule. As-is, this list reproduces the default rule selection.",
        "select = [",
    ]
    grouped = _grouped_by_category(rules)
    for category in sorted(grouped):
        lines.append("")
        lines.append(f"{INDENT}# {category} rules")
        for rule in sorted(grouped[category], key=lambda rule: rule.rule_id):
            enabled = rule.enabled and not rule.is_disabled(target_version)
            comment = f"  # {rule.message}" if rule.message else ""
            if enabled:
                lines.append(f'{INDENT}"{rule.name}",{comment}')
            else:
                note = "project rule" if rule.project_rule else "disabled by default"
                lines.append(f'{INDENT}# "{rule.name}",{comment} ({note})')
    lines.append("]")
    return lines


def _rule_configure_lines(rules: list[Rule]) -> list[str]:
    """Build the commented ``configure`` array documenting every configurable rule parameter."""
    lines = [
        "# Configure rule parameters. Each entry uses the `rule-name.param=value` syntax.",
        "# Uncomment an entry to override the default value shown next to it.",
        "#",
        "# Every rule also accepts a `severity` parameter (E = Error, W = Warning, I = Info) to change how",
        '# its issues are reported, for example: "line-too-long.severity=E".',
        "configure = [",
    ]
    grouped = _grouped_by_category(rules)
    for category in sorted(grouped):
        rules_with_params = [
            rule for rule in sorted(grouped[category], key=lambda rule: rule.rule_id) if list(_iter_rule_params(rule))
        ]
        if not rules_with_params:
            continue
        lines.append("")
        lines.append(f"{INDENT}# {category} rules")
        for rule in rules_with_params:
            lines.append("")
            lines.append(f"{INDENT}# {rule.name}")
            for name, param_type, desc, default in _iter_rule_params(rule):
                if desc:
                    lines.extend(_wrap_comment(f"{name} ({param_type}): {desc}", INDENT))
                else:
                    lines.append(f"{INDENT}# {name} ({param_type})")
                lines.append(f'{INDENT}# "{rule.name}.{name}={format_value(default)}",')
    lines.append("]")
    return lines


def _formatter_lines(formatters: list[Formatter]) -> list[str]:
    """Build the commented ``configure`` array documenting every formatter and its parameters."""
    lines = [
        "# Configure formatter parameters. Each entry uses the `FormatterName.param=value` syntax.",
        "# Uncomment an entry to override the default value shown next to it.",
        "configure = [",
    ]
    for formatter in formatters:
        name = formatter.__class__.__name__
        enabled = getattr(formatter, "ENABLED", True)
        state = "enabled by default" if enabled else "disabled by default (enable it with `FormatterName.enabled=True`)"
        doc = (formatter.__doc__ or "").strip()
        summary = doc.splitlines()[0].strip() if doc else ""
        lines.append("")
        lines.append(f"{INDENT}# {name} ({state})")
        if summary:
            lines.extend(_wrap_comment(summary, INDENT))
        lines.append(f'{INDENT}# "{name}.enabled={format_value(enabled)}",')
        for param in formatter.default_parameters:
            if param.name == "enabled":
                continue
            lines.append(f'{INDENT}# "{name}.{param.name}={format_value(param.value)}",')
    lines.append("]")
    return lines


def generate_config(rules: list[Rule], formatters: list[Formatter], target_version: Version) -> str:
    """Return the full commented configuration file content."""
    lines: list[str] = []
    lines.extend(_generate_header())
    lines.extend(_global_options(target_version))
    lines.extend(_lint_options())
    lines.extend(_rule_select_lines(rules, target_version))
    lines.append("")
    lines.extend(_rule_configure_lines(rules))
    lines.append("")
    lines.extend(_format_options())
    lines.extend(_formatter_lines(formatters))
    lines.append("")
    return "\n".join(lines)
