---
name: End to end tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout Robocop
        uses: actions/checkout@v4
        with:
          path: robocop-repo
          fetch-depth: 2

      - name: Checkout Robot Framework
        uses: actions/checkout@v4
        with:
          repository: robotframework/robotframework
          path: robotframework-repo
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./robocop-repo

      - name: Run e2e test on Robot Framework source code
        run:
          robocop --reports all --configure return_status:quality_gate:E=-1:W=-1:I=-1 robotframework-repo

      - name: Run e2e test on Robocop tests
        run:
          robocop --reports all --configure return_status:quality_gate:E=-1:W=-1:I=-1 robocop-repo
