name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
            python-version: '3.9'
            rf-version: '4.1.3'
          - os: 'ubuntu-latest'
            python-version: '3.10'
            rf-version: '5.0.1'
          - os: 'ubuntu-latest'
            python-version: '3.11'
            rf-version: '6.1.1'
          - os: 'ubuntu-latest'
            python-version: '3.12'
            rf-version: '7.1.1'
          - os: 'ubuntu-latest'
            python-version: '3.13'
            rf-version: '7.2.2'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.13"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install robotframework==${{ matrix.rf-version }}

      - name: Run tests
        run: |
          uv run coverage run --source src/robocop -m pytest
          uv run coverage report
